### ISSUE TITLE
Maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by aaamourao** [dblN/stochastic_depth_keras#3]
Hi, I got a `RuntimeError: maximum recursion depth exceeded in cmp` when running it on a `virtualenv`. It seems related to [Theano Issue #689](https://github.com/Theano/Theano/issues/689). 

I have the following libraries installed on my virtual environment (Keras is installed from `keras-1` branch):

```
Keras==1.0.0
numpy==1.11.0
PyYAML==3.11
scipy==0.17.0
six==1.10.0
Theano==0.8.1
```

**Comment by aaamourao** [comment]
My recursion limit:

``` python
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getrecursionlimit()
1000

```

**Comment by aaamourao** [comment]
It also didn't work downgrading Theano to `v0.8.0`. I'm trying to find a workaround increasing the recursion depth limit. However, It also didn't work under a `2500` depth degree. It's kind of dangerous increasing that, but It's running now with a `3000` depth limit and didn't finish yet. I'm afraid of getting a **bad allocation** before it happens

**Comment by aaamourao** [comment]
A `3000` degree depth length is enough for running the training script. However, it spends at least `8GB` of memory, what is not so bad. I'm going to make a push request now.

**Comment by dblN** [comment]
Thanks. There is a code I inserted already and comment out, so people should do this by themselves.
